server:
  port: 8085

spring:
  application:
    name: transfer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/transfer_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true