server:
  port: 8086

spring:
  application:
    name: kyc-service
  datasource:
    url: jdbc:postgresql://localhost:5432/kyc_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
