server:
  port: 8084

spring:
  application:
    name: ledger-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ledger_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true